# Generated by Django 4.2.21 on 2025-05-21 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(default='', max_length=255)),
                ('date_approvisionnement', models.DateField()),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='', max_length=255)),
                ('statut', models.CharField(default='En attente', max_length=255)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_commande', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(blank=True, default='Attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='article',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='montant_total_article',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='prix_unitaire_vente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10)),
                ('status', models.CharField(default='active', max_length=25)),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montant_total_article', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(default='')),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.commandeclient')),
            ],
        ),
        migrations.CreateModel(
            name='DetailApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montant_total_article', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.approvisionnement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.article')),
            ],
            options={
                'permissions': [('confirm_appro', 'confirmer les approvisionnements')],
            },
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='articles',
            field=models.ManyToManyField(through='MyApp.DetailApprovisionnement', to='MyApp.article'),
        ),
    ]
