# Generated by Django 4.1.7 on 2023-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_commandefournisseur_remove_article_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfacture',
            name='article',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
