# Generated by Django 4.1.7 on 2023-09-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_detailfacture_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(default='', max_length=20)),
                ('date_approvisionnement', models.DateField()),
                ('statut', models.CharField(default='En attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetailApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.approvisionnement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.article')),
            ],
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='articles',
            field=models.ManyToManyField(through='MyApp.DetailApprovisionnement', to='MyApp.article'),
        ),
    ]
