# Generated by Django 4.1.7 on 2023-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_approvisionnement_detailapprovisionnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='montant_total_article',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
