# Generated by Django 4.1.7 on 2023-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_detailapprovisionnement_montant_total_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
