# Generated by Django 4.1.7 on 2023-09-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_approvisionnement_montant_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True)),
                ('Client', models.CharField(default='', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_article', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.commandeclient')),
            ],
        ),
        migrations.RemoveField(
            model_name='lignecommandefournisseur',
            name='article',
        ),
        migrations.RemoveField(
            model_name='lignecommandefournisseur',
            name='commande',
        ),
        migrations.DeleteModel(
            name='CommandeFournisseur',
        ),
        migrations.DeleteModel(
            name='LigneCommandeFournisseur',
        ),
    ]
