# Generated by Django 4.1.7 on 2023-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_commandeclient_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommandeclient',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
