# Generated by Django 4.1.7 on 2023-09-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_lignecommandeclient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeclient',
            name='numero_commande',
        ),
    ]
