# Generated by Django 4.1.7 on 2023-09-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_remove_commandeclient_numero_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
