# Generated by Django 4.1.7 on 2023-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_userplus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='statut',
            field=models.CharField(default='En attente', max_length=25),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
