# Generated by Django 4.1.7 on 2023-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_alter_besoin_statut_alter_commandeclient_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailapprovisionnement',
            options={'permissions': [('confirm_appro', 'confirmer les approvisionnements')]},
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.CharField(default='', max_length=20),
        ),
    ]
