# Generated by Django 4.1.7 on 2023-09-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_detailapprovisionnement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='fournisseur',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(default='En attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='detailapprovisionnement',
            name='montant_total_article',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='detailapprovisionnement',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='article',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='montant_total_article',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='prix_unitaire_vente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='montant_total_article',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
