# Generated by Django 4.2.5 on 2024-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_alter_approvisionnement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfacture',
            name='article',
            field=models.CharField(max_length=255),
        ),
    ]
