# Generated by Django 4.2.5 on 2024-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_alter_detailfacture_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
