# Generated by Django 4.2.5 on 2024-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_facture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(blank=True, default='Attente', max_length=255, null=True),
        ),
    ]
